### ISSUE TITLE
Just some gas optimizations 

### ISSUE THREAD

**Issue by Shymaa-Arafat** [ArkEcosystem/mainsail#300]
**Expected Behavior**

Lines 105 & 106 are kind of unnecessary repetition, 
104     if(
105     _transaction.data.expiration_ &&
106					_transaction.data.expiration > 0_

106 is enough: __if_ expiration>0_ then 105 is necessarily satisfied. I didn't parse the whole code to see whether it's defined as unsigned, if so then 105 is enough and more efficient
(according to https://github.com/code-423n4/2023-10-nextgen/blob/main/4naly3er-report.md#GAS-9 (!=0 consumes less gas than (>0)
-This could apply to line 64 also 
_if (invalidTransactions.length)_
Instead of _if (invalidTransactions.length > 0)
._

**Current Behavior**

**Possible Solution**

**Steps to Reproduce (for bugs)**

**Context**

**Your Environment**

- Version used:
- Environment name and version (e.g. node.js v10.15.3):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by sebastijankuzner** [comment]
Thank you for the report, but I need to clarify that this are TypeScript files which are compiled to the JavaScript code. We don't support solidity at the moment and there is no GAS consumption.

We will keep the existing code for readability.

**Comment by Shymaa-Arafat** [comment]
Oh sorry for this silly mistake, but still why  lines 105&106?
I don't think it provides more readability, in this case you should omit line 105  and keep line 106 (expiration>0)

**Comment by sebastijankuzner** [comment]
Removing suggested line results in the TypeScript error, because expiration is optional property.
