### ISSUE TITLE
Mainsail - future of Ark?

### ISSUE THREAD

**Issue by allexstorm** [ArkEcosystem/mainsail#798]
Hello devs.
As longtime ark holder just want to know what will happen to old ark coin after mainsail mainnet launch?

**Comment by ItsANameToo** [comment]
hey @allexstorm 

Mainsail is an upgrade to the existing ARK network and will replace it when it's ready for production. At that point a snapshot will be made of the existing ARK network and used to start the Mainsail network.

Your funds and votes will automatically transfer to this new network, so you don't need to do anything as a user. Everything will remain working as it did before and you can use your existing passphrase / private key to access your funds and transact with it.

We'll give you plenty of notice before this happens, so make sure to stay tuned to our public channels for updates!
